%%
close('all');
clear();
clc();

%%
% parameters
% - s: `scale`, r: `radius`
syms('s', 'r');
% - radius is always equals `1`
r = 1;
% - min and max of `scale` and `error`
minS = 0;
maxS = 5;
minE = -3;
maxE = (2 * maxS) - (4 * r);
% - conditional points
s1 = (4 / 3) * r;
s2 = 4 * r;
% false positive
% fp = piecewise(...
%     s >= 4*r, (2 * s) - (4 * r), ...
%     s <= (4/3)*r, 0, ...
%     (2 * s) - (4 * r) ...
% );
% 
% fplot(fp, 'LineWidth', 2);

% plot
% - parameters
lineWidth = 2;
fpColor = 'red';
fnColor = 'blue';
probabilityColor = 'green';
hold('on');
% - false positive
fp = fplot(...
    0, [minS, s1], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth, ...
    'DisplayName', 'FP' ...
);
fplot(...
    (2 * s) - (4 * r), [s1, s2], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', ':' ...
);
fplot(...
    (2.5 * s) - (6 * r), [s1, s2], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', '--' ...
);
fplot(...
    (2 * s) - (4 * r), [s2, maxS], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth ...
);

% - false negative
fn = fplot(...
    (4 * r) - (2 * s), [minS, s1], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth ...
);
fplot(...
    0, [s1, s2], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', ':' ...
);
fplot(...
    (2 * r) - (0.5 * s), [s1, s2], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', '--' ...
);
fplot(...
    0, [s2, maxS], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth ...
);

% - probability
pr = fplot(...
    ((4 * r) - s) / s, [s1, s2], ...
    'Color', probabilityColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', '--' ...
);

% - conditional lines
%   - left
line([s1, s1], [minE, maxE], 'Color', 'k', 'LineStyle', '--');
%   - right
line([s2, s2], [minE, maxE], 'Color', 'k', 'LineStyle', '--');
% - set axes
axis([minS, maxS, minE, maxE]);
xlabel('scale');
ylabel('error');
set(gca, ...
    'YTick', [], ...
    'YTickLabel', [], ...
    'Xtick', [s1, s2], ...
    'XTickLabel', {'4/3 r', '4r'} ...
);
legend(...
    [fp, fn, pr], {'FP', 'FN', 'Pr'}, ...
    'Location', 'northwest' ...
);
% - figure
set(gcf, ...
    'Name', 'Error type I, II', ...
    'NumberTitle', 'off', ...
    'Units', 'normalized', ...
    'OuterPosition', [0, 0, 1, 1] ...
);
