%%
close('all');
clear();
clc();

%%
% parameters
% - s: `scale`, r: `radius`
syms('s', 'r');
% - radius is always equals `1`
r = 1;
% - min and max of `scale` and `error`
minS = 0;
maxS = 5;
minE = -3;
maxE = (2 * maxS) - (4 * r);
% - conditional points
s1 = (4 / (3 * sqrt(2))) * r;
s2 = 4 * r;

% plot
% - parameters
lineWidth = 2;
fpColor = 'red';
fnColor = 'blue';
probabilityColor = 'green';
hold('on');
% - false positive
%   - left
fp = fplot(...
    0, ...
    [minS, s1], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth, ...
    'DisplayName', 'FP' ...
);
%   - middle
p = ((2 * s) - (4 * r)) / s;
q = 1 - p;
a = (2 * s) - (4 * r);
b = (1.5 * s) - (2 * r);
fp_ = fplot(...
    (p * a) + (q * ((a + b) / 2)), ...
    [s1, s2], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', '--' ...
);
%   - right
fplot(...
    (4 * s^2) - (pi * 4 * r^2), ...
    [s2, maxS], ...
    'Color', fpColor', ...
    'LineWidth', lineWidth ...
);

% - false negative
%   - left
fn = fplot(...
    (pi * 4 * r^2) - (4 * s^2), ...
    [minS, s1], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth ...
);
%   - middle
a = 0;
b = (2 * r) - (0.5 * s);
fn_ = fplot(...
    (p * a) + (q * ((a + b) / 2)), [s1, s2], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth, ...
    'LineStyle', '--' ...
);
%   - right
fplot(...
    0, ...
    [s2, maxS], ...
    'Color', fnColor', ...
    'LineWidth', lineWidth ...
);

% - conditional lines
%   - left
line([s1, s1], [minE, maxE], 'Color', 'k', 'LineStyle', '--');
%   - right
line([s2, s2], [minE, maxE], 'Color', 'k', 'LineStyle', '--');
% - set axes
axis([minS, maxS, minE, maxE]);
xlabel('scale');
ylabel('error');
set(gca, ...
    'YTick', [0, 1], ...
    'YTickLabel', {'0', '1'}, ...
    'Xtick', [s1, s2], ...
    'XTickLabel', {'4/3 r', '4r'} ...
);
legend(...
    [fp, fp_, fn, fn_], {'FP', 'E[FP]', 'FN', 'E[FN]'}, ...
    'Location', 'northwest' ...
);
% - figure
set(gcf, ...
    'Name', '2D - Error type I, II', ...
    'NumberTitle', 'off', ...
    'Units', 'normalized', ...
    'OuterPosition', [0, 0, 1, 1] ...
);
