%% Initialize
%%
close('all');
clear();
clc();
%% Parameters
%%
std = 1;
maxDistance = 20;
numberOfPoints = 10;
numberOfDimensions = 2;
numberOfSamples = 5;
radius = 1; % alwasy is 1!

addpath('./methods'); 
methods_ = [...
    struct(...
        'handler', @LNN, ...
        'params', [] ...
    ), ...
    struct(...
        'handler', @Grid, ...
        'params', struct('gridResolution', 2) ...
    ) ...
];

info = struct(...
    'numberOfDimensions', numberOfDimensions, ...
    'maxDistance', maxDistance ...
);

configsDir = './assets/configs';
configFilename = '1';
%% Config
%%
% add `methods` to `path`
addpath('./methods');
% make `config`
config = struct(...
    'std', std, ...
    'maxDistance', maxDistance, ...
    'numberOfPoints', numberOfPoints, ...
    'numberOfDimensions', numberOfDimensions, ...
    'numberOfSamples', numberOfSamples, ...
    'radius', radius, ...
    'methods', methods_, ...
    'info', info...
);
% save config
if ~exist(configsDir, 'dir')
    mkdir(configsDir)
end
save(...
    fullfile(configsDir, configFilename), ...
    '-struct', ...
    'config' ...
);

% print `end` message
fprintf(...
    'Make `%s.mat` config file.\n', ...
    fullfile(configsDir, configFilename) ...
);
clear();
